version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5433:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  ###> app ###
  app:
    environment:
      SYMFONY_ENV: dev
      DATABASE_URL: "postgresql://jeremy:jeremy@database:5432/marketplaceAPI?serverVersion=16&charset=utf8"
  ###< app ###
